export const koreanAdvancedCopy = {
  "Speak + transcribe": "음성 출력·받아쓰기",
  "Speak only": "음성 출력만",
  "Start recording": "작업 녹화 시작",
  "Starting…": "시작하는 중…",
  Steps: "실행 단계",
  "Teach a task": "작업 가르치기",
  "Type your answer": "답변을 입력하세요",
  Unassigned: "섹션 없음",
  Unpin: "고정 해제",
  "What to return": "완료 후 전달할 결과",
  "When to use": "언제 사용할지",
  "Default scope": "기본 기억 범위",
  "Manage the workspace semantic memory provider.":
    "작업공간에서 사용할 장기 기억 서비스를 관리합니다.",
  "Not configured": "설정되지 않음",
  "Not connected": "연결되지 않음",
  "Paste a replacement key": "새 API 키를 붙여넣으세요",
  "Paste your API key": "API 키를 붙여넣으세요",
  "Edit Profile": "Bot 정보 수정",
  "Listening…": "듣는 중…",
  "Speaking…": "말하는 중…",
  "Say something. Silence sends it.": "말씀하세요. 잠시 멈추면 자동으로 전송됩니다.",
  "Space interrupts · Esc hangs up": "Space: 끼어들기 · Esc: 통화 종료",
  "Members (pick {min}–{max})": "참여 Bot ({min}~{max}개 선택)",
  "Members ({min}–{max})": "참여 Bot ({min}~{max}개)",
  "Active voice": "현재 목소리",
  "Add to routine": "자동 실행에 추가",
  "API key": "API 키",
  "Bring your own key. The provider is swappable; your bots keep the same speak and call buttons.":
    "사용 중인 서비스의 API 키를 연결하세요. 서비스를 바꿔도 Bot의 읽기·통화 기능은 그대로 유지됩니다.",
  "Connect ElevenLabs, OpenAI, or Cartesia": "ElevenLabs, OpenAI 또는 Cartesia 연결",
  "Keys stay on the server. The app only learns whether a provider is configured.":
    "API 키는 서버에만 안전하게 보관되며, 앱에는 연결 여부만 표시됩니다.",
  "Personal credential": "내 인증 정보",
  Test: "시험 실행",
  "What result will you demonstrate?": "어떤 작업을 직접 보여줄까요?",
  "Export this week's list from the CRM and drop it in the shared folder":
    "CRM에서 이번 주 목록을 내려받아 공유 폴더에 넣기",
  "Teaching needs a graphical sandbox computer. Desktop-host bots can run shell tasks, but not screen recording.":
    "작업을 가르치려면 화면이 있는 샌드박스 컴퓨터가 필요합니다. 내 컴퓨터에서 실행되는 Bot은 터미널 작업은 가능하지만 화면 녹화는 할 수 없습니다.",
  "Open the computer view on web or desktop to teach a task.":
    "작업을 가르치려면 웹이나 데스크톱에서 컴퓨터 화면을 열어주세요.",
  "Where should bots run?": "Bot을 어디에서 실행할까요?",
  "Docker (recommended)": "Docker에서 실행(권장)",
  "Use {name}": "{name} 사용",
  "Docker is the default: bots use a shared Team Computer.":
    "기본 설정은 Docker이며, Bot들이 격리된 팀 컴퓨터를 함께 사용합니다.",
  "Default memory scope": "기본 기억 범위",
  "The selected memory provider is not available in this build.":
    "선택한 기억 서비스는 현재 빌드에서 사용할 수 없습니다.",
  "Add semantic recall alongside native MEMORY.md memory.":
    "기본 MEMORY.md 기억과 함께 의미 기반 장기 기억을 사용합니다.",
  Cloud: "클라우드",
  Local: "로컬",
  "Base URL": "서버 주소",
  "Organization API key": "조직 API 키",
  "Instance API key": "인스턴스 API 키",
  "this Mac": "이 Mac",
  "this computer": "이 컴퓨터",
  "This Mac": "이 Mac",
  "This computer": "이 컴퓨터",
  "macOS will not ask for extra permission if you let bots run on this Mac — they run as you.":
    "이 Mac에서 실행하면 Bot이 내 계정 권한으로 동작하며 macOS가 작업마다 별도 승인을 묻지 않습니다.",
  "Your OS will not ask for extra permission if you let bots run on {name} — they run as you.":
    "{name}에서 실행하면 Bot이 내 계정 권한으로 동작하며 운영체제가 작업마다 별도 승인을 묻지 않습니다.",
  "{name} runs shell commands with your account, including files in your home folder. Do not turn it on for a shared or public server.":
    "{name}에서는 홈 폴더의 파일을 포함해 내 계정 권한으로 터미널 명령을 실행합니다. 여러 사람이 쓰거나 공개된 서버에서는 사용하지 마세요.",
  "Choose a model to get started.": "먼저 사용할 AI 모델을 선택하세요.",
  "Search providers and models": "AI 서비스 또는 모델 검색",
  "Server URL": "모델 서버 주소",
  "OpenAI-compatible server URL": "OpenAI 호환 서버 주소",
  "Setup help": "설정 도움말",
  "Finding…": "찾는 중…",
  "Find models": "모델 찾기",
  Model: "모델",
  "Models from server": "서버에서 찾은 모델",
  "Other model…": "다른 모델 직접 입력…",
  "Model id": "모델 ID",
  "Use a found model": "찾은 모델 중에서 선택",
  "Finish signing in at": "다음 사이트에서 로그인을 마치세요:",
  ". The final page may not load; paste its URL or code here.":
    " 마지막 페이지가 열리지 않아도 괜찮습니다. 그 페이지의 주소나 코드를 아래에 붙여넣으세요.",
  "Authorization code or callback URL": "인증 코드 또는 돌아온 페이지 주소",
  Submit: "확인",
  "Waiting for sign-in…": "로그인 완료를 기다리는 중…",
  "Enter this code at": "다음 사이트에 이 코드를 입력하세요:",
  Optional: "선택 사항",
  "Or paste an API key": "또는 API 키 붙여넣기",
  "This provider cannot paste a key here. Skip if this deployment already has credentials.":
    "이 서비스는 여기에서 API 키를 입력할 수 없습니다. 서버에 이미 인증 정보가 있다면 건너뛰세요.",
  Continue: "계속",
  "Skip for now": "지금은 건너뛰기",
  "Active model": "현재 모델",
  "Loading model catalog…": "모델 목록을 불러오는 중…",
  "Choose which connected model Rakazo uses.":
    "Rakazo에서 기본으로 사용할 연결된 모델을 선택하세요.",
  "Close model settings": "AI 모델 설정 닫기",
  "Deployment default": "서버 기본값",
  "Configured by deployment": "서버에서 설정됨",
  "Search providers": "AI 서비스 검색",
  "No providers found.": "검색된 AI 서비스가 없습니다.",
  "Your key or subscription token is stored securely and is never shown here.":
    "API 키 또는 구독 토큰은 서버에 안전하게 저장되며 이 화면에 다시 표시되지 않습니다.",
  "Connect this provider to use it as your personal model.":
    "이 AI 서비스를 연결하면 내 기본 모델로 사용할 수 있습니다.",
  "Replace API key": "API 키 교체",
  "Or connect an API key": "또는 API 키 연결",
  "Connect API key": "API 키 연결",
  "Switching…": "전환 중…",
  "Use this model": "이 모델 사용",
  "No model catalog is available.": "사용 가능한 모델 목록이 없습니다.",
  "This subscription sign-in is not available in Rakazo yet. Use a deployment credential or choose another provider.":
    "이 구독 로그인 방식은 아직 Rakazo에서 지원되지 않습니다. 서버에 설정된 인증 정보를 사용하거나 다른 서비스를 선택하세요.",
  "Model options": "모델 선택지",
  "Interval amount": "간격 숫자",
  "Interval unit": "간격 단위",
  "Time of day": "실행 시각",
  "Cron expression": "Cron 표현식",
  "Bearer token": "Bearer 토큰",
  "API key header": "API 키 헤더",
  "Close chart": "차트 닫기",
  "Close image preview": "이미지 미리보기 닫기",
  Speak: "읽기",
  Skip: "건너뛰기",
  "I’m done": "조작 끝내기",
  Release: "제어권 돌려주기",
  Team: "팀 공용",
  Private: "Bot 전용",
  Group: "그룹",
  "Select a bot": "대화할 Bot을 선택하세요",
  You: "나",
  archived: "보관됨",
  deleted: "삭제됨",
  bot: "Bot",
  subagent: "보조 에이전트",
  "Archived. Chat, memory, and files kept.": "보관되었습니다. 대화, 기억, 파일은 유지됩니다.",
  "Removed with chat, computer, and memory.": "대화, 컴퓨터, 기억과 함께 삭제되었습니다.",
  "Opened its thread.": "대화가 만들어졌습니다.",
  Waiting: "기다리는 중",
  "Waiting…": "기다리는 중…",
  Authorize: "인증하기",
  Approve: "승인",
  "Connected — its tools are available from your next message.":
    "연결되었습니다. 다음 메시지부터 이 도구를 사용할 수 있습니다.",
  "This server uses browser sign-in. Authorize it to let your agents use its tools — a popup will open.":
    "이 서버는 브라우저 로그인이 필요합니다. 인증을 누르면 새 창이 열리고, 완료 후 Bot이 도구를 사용할 수 있습니다.",
  "Approve this server to let your agent use its tools.":
    "이 서버를 승인하면 Bot이 제공되는 도구를 사용할 수 있습니다.",
  "Dismissed — reconnect anytime from MCP settings.":
    "지금은 연결하지 않았습니다. MCP 설정에서 언제든 다시 연결할 수 있습니다.",
  "Connect MCP server “{name}”": "MCP 서버 ‘{name}’ 연결",
  "OAuth authorization was cancelled.": "OAuth 인증이 취소되었습니다.",
  "OAuth connection failed": "OAuth 연결 실패",
  "Finishing MCP connection…": "MCP 연결을 마무리하는 중…",
  "Return to Rakazo": "Rakazo로 돌아가기",
  "You can close this window.": "이 창을 닫아도 됩니다.",
  "You can close this tab if it does not redirect automatically.":
    "자동으로 이동하지 않으면 이 탭을 닫아도 됩니다.",
  "OAuth connected": "OAuth 연결됨",
  "Authorization expired — reconnect required": "인증이 만료되었습니다. 다시 연결해 주세요",
  "Encrypted static credential saved": "암호화된 인증 정보 저장됨",
  "No credential saved": "저장된 인증 정보 없음",
  "Connect OAuth": "OAuth 연결",
  "Reconnect OAuth": "OAuth 다시 연결",
  "MCP servers": "MCP 서버",
  "Close MCP servers": "MCP 서버 설정 닫기",
  "Connect remote or local tool servers and choose which agents can use them.":
    "원격 또는 로컬 도구 서버를 연결하고 사용할 Bot을 선택하세요.",
  "Add a server": "서버 추가",
  "OAuth will be available for providers that support browser authorization. Static headers work today.":
    "브라우저 인증을 지원하는 서비스는 OAuth로 연결할 수 있습니다. 고정 헤더 인증도 사용할 수 있습니다.",
  "Server name": "서버 이름",
  Command: "실행 명령",
  Arguments: "인자",
  "Access token (optional)": "액세스 토큰(선택 사항)",
  "Stored encrypted": "암호화해 저장",
  "Header value": "헤더 값",
  "Optional header value": "선택 사항인 헤더 값",
  "Adding…": "추가 중…",
  "Add server": "서버 추가",
  "Agent access for new servers": "새 서버를 사용할 Bot",
  "Applies when you click Add server. Use the agent chips on each server card to change access at any time — the agent picks it up on its next message.":
    "서버를 추가할 때 적용됩니다. 각 서버 카드의 Bot 버튼으로 언제든 권한을 바꿀 수 있으며 다음 메시지부터 반영됩니다.",
  "Configured servers": "연결된 서버",
  "No MCP servers yet.": "아직 연결된 MCP 서버가 없습니다.",
  "Agents:": "사용 Bot:",
  "Confirm delete": "삭제 확인",
  "Could not continue": "계속 진행하지 못했습니다.",
  "Could not submit this answer": "답변을 보내지 못했습니다.",
  "This file is not valid UTF-8 Markdown.": "이 파일은 올바른 UTF-8 Markdown 형식이 아닙니다.",
  "Could not load this file.": "파일을 불러오지 못했습니다.",
  "Could not load approval rules": "확인 규칙을 불러오지 못했습니다.",
  "Could not save rule": "확인 규칙을 저장하지 못했습니다.",
  "Could not remove rule": "확인 규칙을 삭제하지 못했습니다.",
  "Could not load voice settings": "음성 설정을 불러오지 못했습니다.",
  "Could not connect this voice provider": "음성 서비스에 연결하지 못했습니다.",
  "Could not save that voice": "목소리를 저장하지 못했습니다.",
  "Could not play a test clip": "샘플 음성을 재생하지 못했습니다.",
  "Microphone failed": "마이크를 사용할 수 없습니다.",
  "Could not send that": "메시지를 보내지 못했습니다.",
  "Could not save that choice": "선택 내용을 저장하지 못했습니다.",
  "Could not complete OAuth": "OAuth 인증을 완료하지 못했습니다.",
  "Could not load integrations": "연동 목록을 불러오지 못했습니다.",
  "Could not connect": "연결하지 못했습니다.",
  "Could not revoke connection": "연결을 해제하지 못했습니다.",
  "Could not install connector": "도구 연결을 추가하지 못했습니다.",
  "Could not remove connector": "도구 연결을 삭제하지 못했습니다.",
  "Could not load MCP servers": "MCP 서버 목록을 불러오지 못했습니다.",
  "Could not add MCP server": "MCP 서버를 추가하지 못했습니다.",
  "Could not start OAuth": "OAuth 인증을 시작하지 못했습니다.",
  "Could not update agent access": "Bot의 서버 사용 권한을 변경하지 못했습니다.",
  "Could not delete MCP server": "MCP 서버를 삭제하지 못했습니다.",
  "Could not disconnect OAuth": "OAuth 연결을 해제하지 못했습니다.",
  "Could not load model settings": "AI 모델 설정을 불러오지 못했습니다.",
  "Could not reach this model server": "모델 서버에 연결하지 못했습니다.",
  "Could not save model": "AI 모델을 저장하지 못했습니다.",
  "Could not change the default model": "기본 모델을 변경하지 못했습니다.",
  "Could not connect this provider": "AI 서비스에 연결하지 못했습니다.",
  "Could not start sign-in": "로그인을 시작하지 못했습니다.",
  "Could not finish sign-in": "로그인을 완료하지 못했습니다.",
  "Could not create your bot": "Bot을 만들지 못했습니다.",
  "Could not create group": "그룹을 만들지 못했습니다.",
  "Failed to send message": "메시지를 보내지 못했습니다.",
  "Failed to stop": "작업을 중지하지 못했습니다.",
  "Could not save routine": "자동 실행을 저장하지 못했습니다.",
  "Could not create bot": "Bot을 만들지 못했습니다.",
  "Could not save": "저장하지 못했습니다.",
  "Could not create section": "섹션을 만들지 못했습니다.",
  "Could not clear conversation": "대화 내용을 비우지 못했습니다.",
  "Could not delete bot": "Bot을 삭제하지 못했습니다.",
  "Could not delete routine": "자동 실행을 삭제하지 못했습니다.",
  "Could not save this choice": "선택 내용을 저장하지 못했습니다.",
  "Could not authorize this app": "앱 인증을 완료하지 못했습니다.",
  "Could not render chart": "차트를 만들지 못했습니다.",
  "Create a section and move {name} into it.": "새 섹션을 만들고 {name}을 옮깁니다.",
  "This permanently removes every message and stops current work. The bot, computer, memory, and routines are kept.":
    "모든 메시지를 영구 삭제하고 진행 중인 작업을 중지합니다. Bot, 컴퓨터, 기억, 자동 실행은 그대로 유지됩니다.",
  "Its conversation, files, and routines will be permanently deleted. Bots it created stay in your list.":
    "대화, 파일, 자동 실행이 영구 삭제됩니다. 이 Bot이 만든 다른 Bot은 목록에 남습니다.",
} as const;
