export const koreanCoreCopy = {
  Account: "계정",
  "Account default": "계정 기본값",
  "Action confirmations": "작업 실행 전 확인",
  Advanced: "고급 설정",
  "Already have an account?": "이미 계정이 있나요?",
  Apps: "앱",
  "Add MCP server": "MCP 서버 추가",
  "Add OpenAPI": "OpenAPI 추가",
  "Add remote MCP server": "원격 MCP 서버 추가",
  "Add Treg": "Treg 추가",
  Archived: "보관됨",
  Asleep: "절전 중",
  "Attach file": "파일 첨부",
  "Bot screen": "Bot 화면",
  "Bot screen preview": "Bot 화면 미리보기",
  Call: "통화",
  Cancel: "취소",
  "Cancel new bot": "새 Bot 만들기 취소",
  "Cancel new group": "새 그룹 만들기 취소",
  "Cancel reply": "답장 취소",
  Close: "닫기",
  "Close computer": "컴퓨터 닫기",
  "Close integrations": "앱·도구 연동 닫기",
  "Close navigation": "메뉴 닫기",
  "Close panel": "패널 닫기",
  Computer: "컴퓨터",
  "Computer failed to boot": "컴퓨터를 시작하지 못했습니다",
  "Computer is asleep": "컴퓨터가 절전 상태입니다",
  "Computer is asleep — take control to wake it":
    "컴퓨터가 절전 중입니다. 직접 조작하면 다시 켜집니다",
  "Computer is stopped": "컴퓨터가 꺼져 있습니다",
  Connected: "연결됨",
  Connect: "연결",
  "Connect apps or add Treg, MCP, and OpenAPI tool sources.":
    "앱을 연결하거나 Treg, MCP, OpenAPI 도구를 추가하세요.",
  "Connect Treg": "Treg 연결",
  "Connecting…": "연결 중…",
  Search: "검색",
  "Connect a model": "AI 모델 연결",
  Create: "만들기",
  "Creating…": "만드는 중…",
  "Create account": "계정 만들기",
  "Create your first bot": "첫 Bot 만들기",
  "Create your Rakazo": "Rakazo 계정 만들기",
  "Continue with email": "이메일로 계속하기",
  "Delete memories too": "기억도 함께 삭제",
  Delete: "삭제",
  "Delete routine": "자동 실행 삭제",
  "Deleting…": "삭제 중…",
  Description: "설명",
  "Describe what this bot does": "이 Bot이 하는 일을 짧게 설명하세요",
  Dictate: "음성 입력",
  "Don’t have an account?": "계정이 없나요?",
  Email: "이메일",
  Export: "내보내기",
  "Hold to talk": "누르고 말하기",
  "Hold to talk (on-device dictation)": "누르고 말하기(기기 내 음성 인식)",
  Instruction: "실행할 내용",
  Integrations: "앱·도구 연동",
  Credential: "인증 정보",
  "Display name": "표시 이름",
  "Header name": "헤더 이름",
  "Import OpenAPI JSON": "OpenAPI JSON 가져오기",
  "Integration views": "연동 목록 보기",
  "Keep memories": "기억은 유지",
  "Inherit default": "기본 설정 사용",
  Isolated: "이 Bot만 사용",
  "Load earlier messages": "이전 메시지 불러오기",
  "Loading integrations…": "연동 목록을 불러오는 중…",
  "Loading rules…": "확인 규칙을 불러오는 중…",
  "Loading…": "불러오는 중…",
  "Log out": "로그아웃",
  Memory: "기억",
  "Memory scope": "기억 사용 범위",
  Message: "메시지",
  "Message…": "메시지를 입력하세요",
  "New bot": "새 Bot 만들기",
  "New group": "새 그룹 만들기",
  "New routine": "새 자동 실행",
  "New section": "새 섹션",
  Models: "AI 모델",
  Name: "이름",
  "Name this bot": "Bot 이름",
  "Name this group": "그룹 이름",
  "No exceptions. Actions run automatically.":
    "별도 확인 규칙이 없습니다. 작업이 자동으로 실행됩니다.",
  "Could not approve this server": "서버를 승인하지 못했습니다.",
  "Could not disconnect memory provider": "기억 서비스 연결을 해제하지 못했습니다.",
  "Could not update the default memory scope": "기본 기억 범위를 변경하지 못했습니다.",
  Attachment: "첨부 파일",
  "Model updated.": "모델이 변경되었습니다.",
  "Saved.": "저장되었습니다.",
  "Now using {name}.": "이제 {name} 모델을 사용합니다.",
  "Connected and using {name}.": "{name}에 연결하고 기본 모델로 설정했습니다.",
  "Message {name}": "{name}에게 메시지 보내기",
  "Remove {name}": "{name} 삭제",
  "Delete {name}": "{name} 삭제",
  "Actions for {name}": "{name} 작업 메뉴",
  "Move {name} to section": "{name} 섹션 이동",
  "{name} is using it": "{name}가 사용 중",
  "{name}’s computer": "{name} 전용 컴퓨터",
  "Clear {name}’s conversation?": "{name}와의 대화 내용을 비울까요?",
  "Delete {name}?": "{name}을 삭제할까요?",
  "Recording: {name}": "녹화 중: {name}",
  "{time} left · bot is watching, not acting":
    "남은 시간 {time} · Bot은 화면만 보고 직접 조작하지 않습니다",
  "Do not type passwords into the demo. Use Take control for credentials.":
    "시연 중에는 비밀번호를 입력하지 마세요. 인증이 필요하면 직접 조작을 사용하세요.",
  "Stop teaching": "가르치기 종료",
  "Bots act without asking by default. Add an exception only when you want to review a type of action first. These preferences apply across all your bots.":
    "Bot은 기본적으로 묻지 않고 작업합니다. 먼저 확인하고 싶은 작업만 예외로 추가하세요. 이 설정은 모든 Bot에 적용됩니다.",
  "Ask before sending external email": "외부 이메일을 보내기 전에 확인",
  "Ask before purchases": "결제하기 전에 확인",
  "Ask before {target}": "{target} 작업 전에 확인",
  "Allow {target} without asking": "{target} 작업은 묻지 않고 허용",
  "Answered: {answer}": "답변 완료: {answer}",
  "Edit first": "수정 후 보내기",
  "Teaching in progress — stop teaching before sending a new message.":
    "작업을 가르치는 중입니다. 새 메시지를 보내려면 먼저 가르치기를 종료하세요.",
  "This bot runs on this computer, not a Linux desktop. Shell and files use your home folder.":
    "이 Bot은 별도 Linux 화면이 아니라 현재 컴퓨터에서 실행됩니다. 터미널과 파일 작업은 홈 폴더를 사용합니다.",
  "This bot runs on this computer. There is no separate Linux desktop. Ask it to use the shell; working directories under your home folder are allowed.":
    "이 Bot은 현재 컴퓨터에서 실행되며 별도 Linux 화면은 없습니다. 터미널을 사용하도록 요청할 수 있고 홈 폴더 아래에서 작업합니다.",
  "Connected {name}.": "{name}에 연결했습니다.",
  "If you heard that, voice is ready.": "샘플이 들렸다면 음성 설정이 완료되었습니다.",
  "Authorization timed out. Please try again.": "인증 시간이 만료되었습니다. 다시 시도해 주세요.",
  "This server cannot be assigned without a bot.":
    "연결할 Bot이 없어 이 서버를 배정할 수 없습니다.",
  "No authentication": "인증 없음",
  "No apps match your search.": "검색 결과가 없습니다.",
  "No connected apps yet.": "아직 연결된 앱이 없습니다.",
  "No MCP or API tool sources installed yet.": "아직 추가된 MCP 또는 API 도구가 없습니다.",
  "Not now": "나중에",
  "Open in full window": "전체 창으로 열기",
  "Open computer": "컴퓨터 열기",
  "Open navigation": "메뉴 열기",
  "Opening your workspace…": "작업공간을 여는 중…",
  Password: "비밀번호",
  Reply: "답장",
  Remove: "삭제",
  "Removing…": "삭제 중…",
  Revoke: "연결 해제",
  "Revoking…": "연결 해제 중…",
  "Replying to": "답장할 메시지",
  Routine: "자동 실행",
  Routines: "자동 실행",
  "Run now": "지금 실행",
  "Running…": "실행 중…",
  Save: "저장",
  "Saving…": "저장 중…",
  Send: "보내기",
  Settings: "설정",
  "Account preferences apply across all your bots.":
    "이 설정은 내가 만든 모든 Bot에 똑같이 적용됩니다.",
  "Optional controls most people never need": "필요할 때만 쓰는 세부 설정",
  "Set up voice to call": "통화하려면 음성을 먼저 설정하세요",
  "Show computer": "컴퓨터 보기",
  "Show settings": "설정 보기",
  "Sign in": "로그인",
  "Sign in to Rakazo": "Rakazo 로그인",
  "Sign up": "가입하기",
  "Search apps": "앱 검색",
  "Speak this reply": "이 답변 읽기",
  Shared: "함께 사용",
  Stop: "중지",
  "Stop dictation": "음성 입력 중지",
  "Stop speaking": "읽기 중지",
  "Take control": "직접 조작",
  "Team Computer": "팀 컴퓨터",
  Title: "역할",
  "Tool sources": "도구 소스",
  "Verify and add": "확인 후 추가",
  "Verifying…": "확인 중…",
  Voice: "음성",
  "Weekly usage": "주간 사용량",
  "Working…": "처리 중…",
  "What about its memories?": "이 Bot의 기억은 어떻게 할까요?",
  "What this bot is for": "이 Bot을 언제, 어떤 일에 사용할지 적어주세요",
  "When to run": "실행 시간",
  "You have control": "직접 조작 중",
  "Your email address": "이메일 주소",
  "Your name": "이름",
  "Your team of always-on agents": "언제든 일을 맡길 수 있는",
  "that you can give real work to.": "나만의 AI 팀",
  "Booting live desktop…": "컴퓨터를 켜는 중…",
  "Clear conversation": "대화 내용 비우기",
  "Clearing…": "비우는 중…",
  Clear: "비우기",
  "Read replies aloud": "답변을 자동으로 읽기",
  "This cannot be undone.": "이 작업은 되돌릴 수 없습니다.",
  "Move them to your shared memory.": "공용 기억으로 옮깁니다.",
  "credential saved": "인증 정보 저장됨",
  "no auth": "인증 없음",
  "Rakazo verifies the source before saving it. Credentials are encrypted and are never returned to clients or exposed to the model.":
    "저장하기 전에 연결 상태를 확인합니다. 인증 정보는 암호화되며 앱이나 AI 모델에 노출되지 않습니다.",
  "No managed app catalog is configured on this deployment. You can still add Treg, MCP, or OpenAPI sources.":
    "이 서버에는 관리형 앱 목록이 설정되지 않았습니다. Treg, MCP 또는 OpenAPI 도구는 직접 추가할 수 있습니다.",
  "Allowed once": "이번만 허용됨",
  "Always allowed": "항상 허용됨",
  Answer: "답변",
  Answered: "답변 완료",
  Archive: "보관",
  "Approval boundaries": "승인이 필요한 범위",
  "Close bot menu": "Bot 메뉴 닫기",
  "Close memory settings": "기억 설정 닫기",
  "Close preview": "미리보기 닫기",
  "Close user settings": "계정 설정 닫기",
  "Close voice settings": "음성 설정 닫기",
  "Create group": "그룹 만들기",
  "Delete group": "그룹 삭제",
  Denied: "거절됨",
  Disconnect: "연결 해제",
  "Disconnecting…": "연결 해제 중…",
  "Draft skill": "작업 기술 초안",
  Duplicate: "복제",
  "Failure handling": "실패했을 때 처리",
  Fullscreen: "전체 화면",
  "Group settings": "그룹 설정",
  "Hear a sample": "샘플 듣기",
  "How to check": "완료 확인 방법",
  "How often": "실행 주기",
  Inputs: "입력값",
  "Loading memory settings…": "기억 설정을 불러오는 중…",
  "Loading preview…": "미리보기를 불러오는 중…",
  "Loading voice providers…": "음성 서비스를 불러오는 중…",
  "Mark as Read": "읽음으로 표시",
  "Mark as Unread": "읽지 않음으로 표시",
  Members: "참여 Bot",
  Minimize: "최소화",
  "Move to": "섹션으로 이동",
  "No longer active": "이미 종료된 요청입니다",
  "No results": "검색 결과가 없습니다",
  Pin: "고정",
  "Pick a voice": "목소리 선택",
  "Playing…": "재생 중…",
  Provider: "서비스",
  Providers: "서비스",
  "Replace key": "키 교체",
  Saved: "저장됨",
  "Saved skills": "저장된 작업 기술",
  "Searching…": "검색 중…",
  "Send answer": "답변 보내기",
  "Send it": "보내기",
  "Sending…": "보내는 중…",
} as const;
